@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": false,
    "cutTests": true,
    "cutClient": false,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 999,
    "backwardDepth": 0,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": true,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "BothDirections" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": false,
    "showMethodParameterNames": false,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 4,
    "showDetailedClassStructure": true
  },
  "rootClass": "DiagramaDeClasse",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_114644 { 
   	label=tcc
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1790324712 { 
   	label=gelato
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   GelatoApplication906396277[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GelatoApplication</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1287436016 { 
   	label=repository
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   R_AcessoViaUrl641479581[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_AcessoViaUrl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ apagarAcessosInvalidos()</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAcessoByTicket(String): Optional&lt;M_AcessoViaUrl&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAcessoByTicketOfTypeValido(String, int): M_AcessoViaUrl</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAcessoByUsuarioAndTypeValido(Long, int): M_AcessoViaUrl</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

R_Compra641479581[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_Compra</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getCompraComProdutoEmTicket(Long, Long, BigDecimal): M_Compra</TD></TR>
<TR><TD ALIGN="LEFT" >+ getComprasDeProdutoComQtdMaiorNoCarrinho(Long, Integer): List&lt;M_Compra&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getQtdComprasDeTicket(Long): Integer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

R_DadosResponsavel641479581[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_DadosResponsavel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getDadosResponsavelByUsuario(Long): List&lt;M_DadosResponsavel&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

R_Transacao641479581[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_Transacao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getSaldoDeCliente(Long): BigDecimal</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTransacoesDeCliente(Long): List&lt;M_Transacao&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

R_Usuario641479581[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_Usuario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getUsuarioByNomeOrEmail(String): M_Usuario</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUsuarioByNomeOrEmailAndSenha(String, String): M_Usuario</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

subgraph cluster_540350491 { 
   	label=produto
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   R_Estoque575498130[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_Estoque</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getEstoqueForProduto(Long): Integer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

R_Produto575498130[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_Produto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getProdutosDisponiveis(): List&lt;M_Produto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getProdutosVendedor(): List&lt;M_Produto&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getQtdDeProdutoEmTicket(Long, Long): Integer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

R_Ticket575498130[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)R_Ticket</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getComprasDeTicket(Long): List&lt;M_Compra&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPedidoFromTicket(Long): M_ViewPedido</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPedidos(): List&lt;M_ViewPedido&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTicketAtivoByString(String): Optional&lt;M_Ticket&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTicketAtivoDeUsuario(Long): Optional&lt;M_Ticket&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ selecionarTicketsDescartaveis(): List&lt;M_Ticket&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];
} 
} 

subgraph cluster_1674944175 { 
   	label=service
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   S_AcessoViaUrl1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_AcessoViaUrl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   r_acessoViaUrl: R_AcessoViaUrl [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Cadastro1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Cadastro</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   encoder: BCryptPasswordEncoder [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   r_dadosResponsavel: R_DadosResponsavel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   r_usuario: R_Usuario [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   senha_valida: Pattern [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Cargo1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Cargo</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Compra1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Compra</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   r_compra: R_Compra [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Estoque1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Estoque</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   r_estoque: R_Estoque [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_JavaMailSender1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_JavaMailSender</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   javaMailSender: JavaMailSender [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   templateEngine: TemplateEngine [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Login1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Login</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   authenticationManager: AuthenticationManager [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   securityContextRepository: SecurityContextRepository [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Produto1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Produto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   r_produto: R_Produto [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Ticket1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Ticket</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   r_compra: R_Compra [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   r_ticket: R_Ticket [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

S_Transacao1952781372[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)S_Transacao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   r_transacao: R_Transacao [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1694159202 { 
   	label=controller
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   C_Cadastro1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Cadastro</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   s_acessoViaUrl: S_AcessoViaUrl [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_cadastro: S_Cadastro [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_javaMailSender: S_JavaMailSender [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Catalogo1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Catalogo</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   s_cargo: S_Cargo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_produto: S_Produto [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Error1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Error</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Inicio1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Inicio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   context: ApplicationContext [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_acessoViaUrl: S_AcessoViaUrl [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Login1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Login</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   s_acessoViaUrl: S_AcessoViaUrl [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_cargo: S_Cargo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_compra: S_Compra [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_javaMailSender: S_JavaMailSender [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_login: S_Login [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_ticket: S_Ticket [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_transacao: S_Transacao [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Pedidos1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Pedidos</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   s_cadastro: S_Cadastro [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_cargo: S_Cargo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_ticket: S_Ticket [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   templateEngine: TemplateEngine [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Produto1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Produto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   s_cargo: S_Cargo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_compra: S_Compra [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_estoque: S_Estoque [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_produto: S_Produto [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_ticket: S_Ticket [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Ticket1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Ticket</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   s_cargo: S_Cargo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_compra: S_Compra [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_estoque: S_Estoque [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_ticket: S_Ticket [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_transacao: S_Transacao [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

C_Transacao1954851659[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)C_Transacao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   s_cadastro: S_Cadastro [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_cargo: S_Cargo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   s_transacao: S_Transacao [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1804629597 { 
   	label=model
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   M_AcessoViaUrl2054619536[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_AcessoViaUrl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   funcionalidade: Funcionalidade [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ticket: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usuario: M_Usuario [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   validade: LocalDateTime [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_Compra2054619536[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_Compra</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   horario: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   preco: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   produto: M_Produto [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quantidade: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ticket: M_Ticket [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_DadosResponsavel2054619536[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_DadosResponsavel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   contato: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   filiacao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usuario: M_Usuario [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_MetodoPagamento2054619536[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_MetodoPagamento</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   metodo: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tipo: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   vendedor: M_Usuario [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_Transacao2054619536[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_Transacao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   ao_vendedor: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   cliente: M_Usuario [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   horario_fornecido: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   valida: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   valor: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   vendedor: M_Usuario [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_Usuario2054619536[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_Usuario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   cargo: Cargo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   senha: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   telefone: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   verificado: Boolean [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1178372080 { 
   	label=view
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   M_ViewPedido532415645[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)M_ViewPedido</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getContagem_negativa(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ getContagem_retirada(): PGInterval</TD></TR>
<TR><TD ALIGN="LEFT" >+ getHorario_encaminhado(): LocalDateTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ getHorario_retirada_final(): LocalDateTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ getHorario_retirada_planejado(): LocalDateTime</TD></TR>
<TR><TD ALIGN="LEFT" >+ getId_ticket(): Long</TD></TR>
<TR><TD ALIGN="LEFT" >+ getNome_cliente(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getObservacao(): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPreco(): BigDecimal</TD></TR>
<TR><TD ALIGN="LEFT" >+ getStatus(): StatusCompra</TD></TR>
<TR><TD ALIGN="LEFT" >+ getStatus_id(): Short</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTicket(): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];
} 

subgraph cluster_1399127407 { 
   	label=M_Usuario
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   Cargo1365861602[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)Cargo</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   CLIENTE: Cargo [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   VENDEDOR: Cargo [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];
} 

subgraph cluster_1416435118 { 
   	label=produto
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   Avaliacao394890476[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)Avaliacao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   ADOREI: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   AMEI: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   BOM: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   DELICIOSO: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   GOSTOSO: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   NAO_GOSTEI: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   ODIEI: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   OK: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   PERFEITO: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   QUESTIONAVEL: Avaliacao [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];

M_Avaliacao643863173[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_Avaliacao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   anonima: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   avaliacao: Avaliacao [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   descricao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   horario: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   produto: M_Produto [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   publica: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usuario: M_Usuario [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   vendedor_desabilitar: M_Usuario [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_Estoque643863173[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_Estoque</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   horario: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   produto: M_Produto [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quantidade: Integer [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_Produto643863173[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_Produto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   descricao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   disponivel: boolean [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   estoque_minimo: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   medida: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   nome: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   preco: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   url_icone: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_Ticket643863173[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_Ticket</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   horario_fornecido: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   horario_retirada_final: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   horario_retirada_planejado: LocalDateTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   observacao: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   pagamento: M_Transacao [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   status: StatusCompra [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   ticket: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usuario: M_Usuario [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

StatusCompra1199067761[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)StatusCompra</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   CANCELADO: StatusCompra [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   CARRINHO: StatusCompra [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   ENCAMINHADO: StatusCompra [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   ENTREGUE: StatusCompra [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   PREPARADO: StatusCompra [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   RECEBIDO: StatusCompra [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];
} 

subgraph cluster_503580362 { 
   	label=M_AcessoViaUrl
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   Funcionalidade1914879581[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)Funcionalidade</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   RECUPERAR_SENHA: Funcionalidade [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   VERIFICAR_CONTA: Funcionalidade [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];
} 

subgraph cluster_952195777 { 
   	label=servidor
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   M_Navbar396933358[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)M_Navbar</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

M_NavbarCliente396933358[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_NavbarCliente</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   quantidade_compras: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   saldo: BigDecimal [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_Resposta396933358[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)M_Resposta</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getMensagem(): Object</TD></TR>
<TR><TD ALIGN="LEFT" >+ isSucesso(): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ setMensagem(Object)</TD></TR>
<TR><TD ALIGN="LEFT" >+ setSucesso(Boolean)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

M_RespostaObjeto396933358[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_RespostaObjeto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mensagem: Object [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sucesso: Boolean [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

M_RespostaTexto396933358[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)M_RespostaTexto</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mensagem: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sucesso: Boolean [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 
} 
} 

subgraph cluster_1234099708 { 
   	label=DiagramaDeClasse
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   DiagramaDeClasse1234099708[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DiagramaDeClasse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >#   c_cadastro: C_Cadastro [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_catalogo: C_Catalogo [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_error: C_Error [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_inicio: C_Inicio [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_login: C_Login [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_pedidos: C_Pedidos [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_produto: C_Produto [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_ticket: C_Ticket [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   c_transacao: C_Transacao [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   gelatoApplication: GelatoApplication [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_acessoViaUrl: M_AcessoViaUrl [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_avaliacao: M_Avaliacao [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_compra: M_Compra [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_dadosResponsavel: M_DadosResponsavel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_estoque: M_Estoque [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_metodoPagamento: M_MetodoPagamento [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_navbar: M_Navbar [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_produto: M_Produto [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_resposta: M_Resposta [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_ticket: M_Ticket [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_transacao: M_Transacao [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_usuario: M_Usuario [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   m_viewPedido: M_ViewPedido [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
C_Cadastro1954851659 -> S_AcessoViaUrl1952781372[label="s_acessoViaUrl
[0..1]"];
C_Cadastro1954851659 -> S_Cadastro1952781372[label="s_cadastro
[0..1]"];
C_Cadastro1954851659 -> S_JavaMailSender1952781372[label="s_javaMailSender
[0..1]"];
C_Catalogo1954851659 -> S_Cargo1952781372[label="s_cargo
[0..1]"];
C_Catalogo1954851659 -> S_Produto1952781372[label="s_produto
[0..1]"];
C_Inicio1954851659 -> C_Ticket1954851659[label="diario() -> apagarTicketsVazios()"];
C_Inicio1954851659 -> S_AcessoViaUrl1952781372[label="s_acessoViaUrl
[0..1]"];
C_Login1954851659 -> S_AcessoViaUrl1952781372[label="s_acessoViaUrl
[0..1]"];
C_Login1954851659 -> S_Cargo1952781372[label="s_cargo
[0..1]"];
C_Login1954851659 -> S_Compra1952781372[label="s_compra
[0..1]"];
C_Login1954851659 -> S_JavaMailSender1952781372[label="s_javaMailSender
[0..1]"];
C_Login1954851659 -> S_Login1952781372[label="s_login
[0..1]"];
C_Login1954851659 -> S_Ticket1952781372[label="s_ticket
[0..1]"];
C_Login1954851659 -> S_Transacao1952781372[label="s_transacao
[0..1]"];
C_Pedidos1954851659 -> S_Cadastro1952781372[label="s_cadastro
[0..1]"];
C_Pedidos1954851659 -> S_Cargo1952781372[label="s_cargo
[0..1]"];
C_Pedidos1954851659 -> S_Ticket1952781372[label="s_ticket
[0..1]"];
C_Produto1954851659 -> S_Cargo1952781372[label="s_cargo
[0..1]"];
C_Produto1954851659 -> S_Compra1952781372[label="s_compra
[0..1]"];
C_Produto1954851659 -> S_Estoque1952781372[label="s_estoque
[0..1]"];
C_Produto1954851659 -> S_Produto1952781372[label="s_produto
[0..1]"];
C_Produto1954851659 -> S_Ticket1952781372[label="s_ticket
[0..1]"];
C_Ticket1954851659 -> S_Cargo1952781372[label="s_cargo
[0..1]"];
C_Ticket1954851659 -> S_Compra1952781372[label="s_compra
[0..1]"];
C_Ticket1954851659 -> S_Estoque1952781372[label="s_estoque
[0..1]"];
C_Ticket1954851659 -> S_Ticket1952781372[label="s_ticket
[0..1]"];
C_Ticket1954851659 -> S_Transacao1952781372[label="s_transacao
[0..1]"];
C_Transacao1954851659 -> S_Cadastro1952781372[label="s_cadastro
[0..1]"];
C_Transacao1954851659 -> S_Cargo1952781372[label="s_cargo
[0..1]"];
C_Transacao1954851659 -> S_Transacao1952781372[label="s_transacao
[0..1]"];
DiagramaDeClasse1234099708 -> C_Cadastro1954851659[label="c_cadastro
[0..1]"];
DiagramaDeClasse1234099708 -> C_Catalogo1954851659[label="c_catalogo
[0..1]"];
DiagramaDeClasse1234099708 -> C_Error1954851659[label="c_error
[0..1]"];
DiagramaDeClasse1234099708 -> C_Inicio1954851659[label="c_inicio
[0..1]"];
DiagramaDeClasse1234099708 -> C_Login1954851659[label="c_login
[0..1]"];
DiagramaDeClasse1234099708 -> C_Pedidos1954851659[label="c_pedidos
[0..1]"];
DiagramaDeClasse1234099708 -> C_Produto1954851659[label="c_produto
[0..1]"];
DiagramaDeClasse1234099708 -> C_Ticket1954851659[label="c_ticket
[0..1]"];
DiagramaDeClasse1234099708 -> C_Transacao1954851659[label="c_transacao
[0..1]"];
DiagramaDeClasse1234099708 -> GelatoApplication906396277[label="gelatoApplication
[0..1]"];
DiagramaDeClasse1234099708 -> M_AcessoViaUrl2054619536[label="m_acessoViaUrl
[0..1]"];
DiagramaDeClasse1234099708 -> M_Avaliacao643863173[label="m_avaliacao
[0..1]"];
DiagramaDeClasse1234099708 -> M_Compra2054619536[label="m_compra
[0..1]"];
DiagramaDeClasse1234099708 -> M_DadosResponsavel2054619536[label="m_dadosResponsavel
[0..1]"];
DiagramaDeClasse1234099708 -> M_Estoque643863173[label="m_estoque
[0..1]"];
DiagramaDeClasse1234099708 -> M_MetodoPagamento2054619536[label="m_metodoPagamento
[0..1]"];
DiagramaDeClasse1234099708 -> M_Navbar396933358[label="m_navbar
[0..1]"];
DiagramaDeClasse1234099708 -> M_Produto643863173[label="m_produto
[0..1]"];
DiagramaDeClasse1234099708 -> M_Resposta396933358[label="m_resposta
[0..1]"];
DiagramaDeClasse1234099708 -> M_Ticket643863173[label="m_ticket
[0..1]"];
DiagramaDeClasse1234099708 -> M_Transacao2054619536[label="m_transacao
[0..1]"];
DiagramaDeClasse1234099708 -> M_Usuario2054619536[label="m_usuario
[0..1]"];
DiagramaDeClasse1234099708 -> M_ViewPedido532415645[label="m_viewPedido
[0..1]"];
M_AcessoViaUrl2054619536 -> Funcionalidade1914879581[label="funcionalidade
[0..1]"];
M_AcessoViaUrl2054619536 -> M_Usuario2054619536[label="usuario
[0..1]"];
M_Avaliacao643863173 -> Avaliacao394890476[label="avaliacao
[0..1]"];
M_Avaliacao643863173 -> M_Produto643863173[label="produto
[0..1]"];
M_Avaliacao643863173 -> M_Usuario2054619536[label="usuario
[0..1]"];
M_Avaliacao643863173 -> M_Usuario2054619536[label="vendedor_desabilitar
[0..1]"];
M_Compra2054619536 -> M_Produto643863173[label="produto
[0..1]"];
M_Compra2054619536 -> M_Ticket643863173[label="ticket
[0..1]"];
M_DadosResponsavel2054619536 -> M_Usuario2054619536[label="usuario
[0..1]"];
M_Estoque643863173 -> M_Produto643863173[label="produto
[0..1]"];
M_MetodoPagamento2054619536 -> M_Usuario2054619536[label="vendedor
[0..1]"];
M_Navbar396933358 -> M_NavbarCliente396933358[arrowhead=none, arrowtail=empty, dir=both];
M_Resposta396933358 -> M_RespostaObjeto396933358[arrowhead=none, arrowtail=empty, dir=both];
M_Resposta396933358 -> M_RespostaTexto396933358[arrowhead=none, arrowtail=empty, dir=both];
M_Ticket643863173 -> M_Transacao2054619536[label="pagamento
[0..1]"];
M_Ticket643863173 -> M_Usuario2054619536[label="usuario
[0..1]"];
M_Ticket643863173 -> StatusCompra1199067761[label="status
[0..1]"];
M_Transacao2054619536 -> M_Usuario2054619536[label="cliente
[0..1]"];
M_Transacao2054619536 -> M_Usuario2054619536[label="vendedor
[0..1]"];
M_Usuario2054619536 -> Cargo1365861602[label="cargo
[0..1]"];
M_ViewPedido532415645 -> StatusCompra1199067761[label="getStatus() -> index()"];
S_AcessoViaUrl1952781372 -> R_AcessoViaUrl641479581[label="r_acessoViaUrl
[0..1]"];
S_Cadastro1952781372 -> R_DadosResponsavel641479581[label="r_dadosResponsavel
[0..1]"];
S_Cadastro1952781372 -> R_Usuario641479581[label="r_usuario
[0..1]"];
S_Compra1952781372 -> R_Compra641479581[label="r_compra
[0..1]"];
S_Estoque1952781372 -> R_Estoque575498130[label="r_estoque
[0..1]"];
S_Produto1952781372 -> R_Produto575498130[label="r_produto
[0..1]"];
S_Ticket1952781372 -> R_Compra641479581[label="r_compra
[0..1]"];
S_Ticket1952781372 -> R_Ticket575498130[label="r_ticket
[0..1]"];
S_Ticket1952781372 -> S_Compra1952781372[label="desativarProdutosEmTicketComEstoqueInsuficiente() -> desativarComEstoqueInsuficiente()"];
S_Ticket1952781372 -> S_Estoque1952781372[label="desativarProdutosEmTicketComEstoqueInsuficiente() -> getEstoqueForProduto()"];
S_Ticket1952781372 -> S_Transacao1952781372[label="encaminharTicket() -> alterarSaldo()"];
S_Ticket1952781372 -> StatusCompra1199067761[label="avancarTicket() -> index()"];
S_Transacao1952781372 -> R_Transacao641479581[label="r_transacao
[0..1]"];
    
}
@enduml